name: git-fame
summary: Pretty-print `git` repository collaborators sorted by contributions
description: |
 {description}
adopt-info: git-fame
grade: stable
confinement: strict
base: core18
license: MPL-2.0
parts:
  git-fame:
    plugin: python
    python-packages: [tqdm, pyyaml]
    stage-packages: [git]
    source: {source}
    source-commit: '{commit}'
    parse-info: [setup.py]
    override-build: |
        snapcraftctl build
        cp $SNAPCRAFT_PART_BUILD/git-fame_completion.bash $SNAPCRAFT_PART_INSTALL/completion.sh
apps:
  git-fame:
    command: bin/git-fame
    completer: completion.sh
    plugs: [home]
